//! CABAC arithmetic decoding engine + context initialisation (thesis Ch4 §4.4.2).
//!
//! Ported from FFmpeg's libavcodec/cabac_functions.h + cabac.c + h264_cabac.c.
//! Uses FFmpeg's combined-state model (one byte per context encoding both the
//! probability state and MPS), so the generated `LPS_RANGE` / `MLPS_STATE` /
//! `NORM_SHIFT` tables and the context-init formula are used verbatim — see
//! `thesis_cabac_tables.rs` (generated by scripts/gen_cabac_tables.py).
//!
//! The byte refill uses FFmpeg's 2-byte (CABAC_BITS=16) scheme in its
//! even-aligned form. CABAC decoding is alignment-invariant — the decoded bins
//! depend only on the byte values — so emulating an even-aligned buffer is a
//! complete, correct decoder.
//!
//! This is the entropy engine only. The CABAC macroblock layer (binarization,
//! mb_skip/mb_type/ref/mvd, residual significance maps) is a later installment;
//! it reuses the same grids/prediction/export as the CAVLC path.

use super::custom_cabac_tables::{CTX_INIT_I, CTX_INIT_PB, LPS_RANGE, MLPS_STATE, NORM_SHIFT};

const CABAC_MASK: i64 = 0xFFFF; // (1 << CABAC_BITS) - 1, CABAC_BITS = 16

/// FFmpeg-model CABAC decoder over a byte buffer (the slice RBSP from the
/// byte-aligned start of slice_data).
pub struct Cabac<'a> {
    low: i64,
    range: i64,
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Cabac<'a> {
    /// Initialise from `bytes` starting at byte offset `start` (after the
    /// cabac_alignment_one_bit byte alignment).
    pub fn new(bytes: &'a [u8], start: usize) -> Self {
        let mut c = Cabac {
            low: 0,
            range: 0x1FE,
            bytes,
            pos: start,
        };
        c.low = (c.byte(0) << 18) + (c.byte(1) << 10);
        c.low += 1 << 9; // even-aligned init
        c.pos = start + 2;
        c
    }

    #[inline]
    fn byte(&self, k: usize) -> i64 {
        *self.bytes.get(self.pos + k).unwrap_or(&0) as i64
    }

    #[inline]
    fn refill(&mut self) {
        self.low += (self.byte(0) << 9) + (self.byte(1) << 1);
        self.low -= CABAC_MASK;
        self.pos += 2;
    }

    #[inline]
    fn refill2(&mut self) {
        let i = (self.low as u64).trailing_zeros() as i64 - 16; // ctz(low) - CABAC_BITS
        let x = -CABAC_MASK + (self.byte(0) << 9) + (self.byte(1) << 1);
        self.low += x << i;
        self.pos += 2;
    }

    /// Decode one regular bin against context `state` (updated in place).
    ///
    /// Table lookups are `get_unchecked`: the combined state is always 0..=127
    /// (init clamps ≤125; every `MLPS_STATE` entry is ≤127), so `127-s`/`128+s`
    /// land in 0..256 and `range & 511` in 0..512. The LPS/MPS branch is kept
    /// (not made branchless): context-modelled bins are skewed enough that the
    /// predictor wins, and a measured branchless variant was ~10% slower.
    #[inline]
    pub fn get(&mut self, state: &mut u8) -> u32 {
        let s = (*state & 127) as usize;
        let q = ((self.range >> 6) & 3) as usize;
        let range_lps = unsafe { *LPS_RANGE.get_unchecked(q * 128 + s) } as i64;
        self.range -= range_lps;
        let bit;
        if self.low > (self.range << 17) {
            // LPS (FFmpeg lps_mask = (range<<17 - low) >> 31; equality => MPS)
            self.low -= self.range << 17;
            self.range = range_lps;
            *state = unsafe { *MLPS_STATE.get_unchecked(127 - s) };
            bit = ((s & 1) ^ 1) as u32;
        } else {
            // MPS
            *state = unsafe { *MLPS_STATE.get_unchecked(128 + s) };
            bit = (s & 1) as u32;
        }
        let shift = unsafe { *NORM_SHIFT.get_unchecked((self.range & 511) as usize) } as i64;
        self.range <<= shift;
        self.low <<= shift;
        if self.low & CABAC_MASK == 0 {
            self.refill2();
        }
        bit
    }

    /// Decode one bypass (equiprobable) bin.
    #[inline]
    pub fn bypass(&mut self) -> u32 {
        self.low += self.low;
        if self.low & CABAC_MASK == 0 {
            self.refill();
        }
        let range = self.range << 17;
        if self.low < range {
            0
        } else {
            self.low -= range;
            1
        }
    }

    /// Decode `n` bypass bins as an unsigned value (MSB first).
    pub fn bypass_bits(&mut self, n: u32) -> u32 {
        let mut v = 0;
        for _ in 0..n {
            v = (v << 1) | self.bypass();
        }
        v
    }

    /// Bypass-decode a sign bit applied to `val` (FFmpeg get_cabac_bypass_sign).
    /// Returns `val` when the sign bit is 0, `-val` when 1.
    #[inline]
    pub fn bypass_sign(&mut self, val: i32) -> i32 {
        self.low += self.low;
        if self.low & CABAC_MASK == 0 {
            self.refill();
        }
        let mut range = self.range << 17;
        self.low -= range;
        let mask: i64 = if self.low < 0 { -1 } else { 0 };
        range &= mask;
        self.low += range;
        (val ^ mask as i32) - mask as i32
    }

    /// Decode the terminate bin (end_of_slice_flag / I_PCM). Returns true when
    /// the terminate symbol (1) is decoded.
    #[inline]
    pub fn terminate(&mut self) -> bool {
        self.range -= 2;
        if self.low < (self.range << 17) {
            let shift = if self.range < 0x100 { 1 } else { 0 };
            self.range <<= shift;
            self.low <<= shift;
            if self.low & CABAC_MASK == 0 {
                self.refill();
            }
            false
        } else {
            true
        }
    }

    /// Current byte offset (for diagnostics / I_PCM realignment).
    pub fn byte_pos(&self) -> usize {
        self.pos
    }

    /// Backing buffer (for I_PCM engine re-init).
    pub fn bytes_ref(&self) -> &'a [u8] {
        self.bytes
    }

    /// Byte position of the I_PCM raw data (FFmpeg: bytestream adjusted by the
    /// low register's buffered bits, CABAC_BITS=16).
    pub fn pcm_byte_pos(&self) -> usize {
        let mut p = self.pos;
        if self.low & 1 != 0 {
            p -= 1;
        }
        if self.low & 0x1FF != 0 {
            p -= 1;
        }
        p
    }
}

/// Initialise the 1024 CABAC context states (FFmpeg ff_h264_init_cabac_states).
/// `slice_type_i` selects the I table; otherwise `cabac_init_idc` (0..2) picks a
/// P/B table. `slice_qp` is SliceQP_Y.
pub fn init_states(
    states: &mut [u8; 1024],
    slice_type_i: bool,
    cabac_init_idc: usize,
    slice_qp: i32,
) {
    let qp = slice_qp.clamp(0, 51);
    let base = |i: usize| -> (i32, i32) {
        if slice_type_i {
            (CTX_INIT_I[2 * i] as i32, CTX_INIT_I[2 * i + 1] as i32)
        } else {
            let off = cabac_init_idc.min(2) * 2048;
            (CTX_INIT_PB[off + 2 * i] as i32, CTX_INIT_PB[off + 2 * i + 1] as i32)
        }
    };
    for i in 0..1024 {
        let (m, n) = base(i);
        let mut pre = 2 * (((m * qp) >> 4) + n) - 127;
        pre ^= pre >> 31;
        if pre > 124 {
            pre = 124 + (pre & 1);
        }
        states[i] = pre as u8;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn context_init_qp_known() {
        // Spot-check the init formula against the spec relationship: for the
        // combined state, state>>1 is pStateIdx and the result is in [0,124(+1)].
        let mut st = [0u8; 1024];
        init_states(&mut st, true, 0, 26);
        assert!(st.iter().all(|&s| s <= 125));
    }

    #[test]
    fn terminate_does_not_panic_on_short_buffer() {
        // A tiny buffer must not index out of bounds (byte() returns 0 past end).
        let buf = [0x80u8, 0x00, 0x00, 0x00];
        let mut c = Cabac::new(&buf, 0);
        let _ = c.bypass();
        let _ = c.terminate();
    }
}
