use std::ffi::CStr;
use std::fs::File;
use std::io::BufWriter;
use std::ffi::CString;
use std::ptr;
use std::sync::OnceLock;

use ffmpeg_sys_next::{self as ff, AVMotionVector};
use mv_types::motion_vector::{MotionVector, MotionVectorCsvWriter, MvCompactCsvWriter};

/// Mirror of the C struct added by the custom FFmpeg patch.
/// Not generated by bindgen because ffmpeg-sys-next's allowlist only covers
/// the upstream AVMotionVector; layout must stay in sync with motion_vector.h.
#[cfg(feature = "custom_ffmpeg")]
#[repr(C)]
pub struct AVMotionVectorCompact {
    pub source: i32,
    pub src_x: i16,
    pub src_y: i16,
    pub dst_x: i16,
    pub dst_y: i16,
}
#[cfg(feature = "custom_ffmpeg")]
use mv_types::motion_vector::MvCompact;

/// CLI arguments shared by every extractor binary.
///
/// Layout: `<input file> <print mv> <output file> <is verbose> <thread count>`
pub struct ExtractorArgs {
    pub video_file: String,
    pub do_print: bool,
    pub output_file: String,
    pub is_verbose: bool,
    /// Worker count: 0 = auto (all cores), 1 = serial, N = N workers.
    ///
    /// This used to be parsed as a boolean `is_single_threaded`, but the
    /// benchmark harness passes a thread *count* here (1, 2, 4 … 128) exactly
    /// as it does to extractor0..7 — so every non-zero value meant "single
    /// threaded" and the worker pool below was unreachable from a benchmark
    /// run at any setting. 0 and 1 keep their previous meaning; only >= 2
    /// changes behaviour, and only from "serial" to what it says.
    pub thread_count: i32,
    /// Opt-in H.264 B-slice (bi-predictive) decode. Off by default so the CLI
    /// contract and output stay unchanged for existing callers/scripts;
    /// enabled via `E9_B_SLICES=1` rather than a new positional argument.
    /// Forces the serial decode path (B-slice direct mode needs the DPB of
    /// already-decoded reference pictures, which the parallel worker-pool
    /// path doesn't have).
    pub decode_b_slices: bool,
    /// Opt-in: drop list-1 (`source > 0`, forward-reference) rows from the
    /// export, keeping only list-0. Matches the custom FFmpeg fork's
    /// `mv_l0_only` AVOption (set unconditionally by extractor1/3/5/6) — off
    /// by default here since this decoder's whole point is the complete
    /// motion field, not reproducing that debug-mode subset. Enabled via
    /// `E9_L0_ONLY=1` rather than a new positional argument, matching
    /// `E9_B_SLICES`'s convention.
    pub l0_only: bool,
}

impl ExtractorArgs {
    pub fn from_env() -> Option<Self> {
        let argv: Vec<String> = std::env::args().collect();
        if argv.len() < 6 {
            let exe = argv.first().cloned().unwrap_or_else(|| "extractor".to_string());
            eprintln!(
                "Usage: {} <input file> <print mv> <output file> <is verbose> <thread count>",
                exe
            );
            return None;
        }
        Some(Self {
            video_file: argv[1].clone(),
            do_print: argv[2].parse::<i32>().unwrap_or(0) != 0,
            output_file: argv[3].clone(),
            is_verbose: argv[4].parse::<i32>().unwrap_or(0) != 0,
            thread_count: argv[5].parse::<i32>().unwrap_or(0),
            decode_b_slices: std::env::var("E9_B_SLICES").map(|v| v != "0").unwrap_or(false),
            l0_only: std::env::var("E9_L0_ONLY").map(|v| v != "0").unwrap_or(false),
        })
    }
}

fn env_i32(key: &str) -> i32 {
    std::env::var(key).ok().and_then(|v| v.trim().parse().ok()).unwrap_or(0)
}

/// Motion-vector post-filters, shared by the H.264 and HEVC export paths and
/// mirroring the custom FFmpeg fork's `mv_min_size` / `mv_grid` options (see
/// `libavcodec/mpegutils.h`'s `FFMvFilter`) so extractor9's output stays
/// directly comparable with extractor1/3/5/6 under the same settings.
///
/// * `MV_MIN_SIZE=N` — drop vectors whose displacement is shorter than N pixels.
/// * `MV_GRID=N`     — keep at most one vector per N x N pixel cell.
///
/// Both default to 0 (off), so an unset environment exports exactly what it did
/// before these existed. The threshold runs first and the grid second, so a cell
/// is claimed by a vector that actually passed the threshold.
///
/// The grid replaced an earlier "keep 1 of every N vectors in decode order"
/// filter, which sampled by the macroblock walk and therefore clustered
/// arbitrarily; cells spread the kept field over the picture instead.
///
/// Read directly from the makefile's `MV_GRID`/`MV_MIN_SIZE` (exported via
/// `BENCH_ENV`, inherited by this process) rather than through an `E9_`-prefixed
/// relay like `E9_L0_ONLY`. Those relays exist because extractor9's default
/// differs from the makefile variable's; these are 0-by-default everywhere.
///
/// Construct one per export call: the occupancy set must restart each picture.
/// Skip every Nth picture entirely, in decode order — the counterpart of the
/// fork's `mv_skip_every_nth`. Unlike the vector filters above this genuinely
/// saves time: a skipped picture is never parsed.
///
/// 0 or 1 decodes everything; 2 drops half, 3 drops a third, 4 a quarter, so
/// larger N is a *gentler* trim. Skipped pictures cannot be recovered
/// afterwards, which is why the useful range is a mild one.
pub fn mv_skip_every_nth() -> i32 {
    static N: OnceLock<i32> = OnceLock::new();
    *N.get_or_init(|| env_i32("MV_SKIP_EVERY_NTH"))
}

pub struct MvFilter {
    min_size: i32,
    grid: i32,
    seen: std::collections::HashSet<(i32, i32)>,
}

impl MvFilter {
    pub fn new() -> Self {
        // Parsed once per process, like `dbg_enabled()`'s E10_DBG in hevc_slice.
        static PARAMS: OnceLock<(i32, i32)> = OnceLock::new();
        let (min_size, grid) =
            *PARAMS.get_or_init(|| (env_i32("MV_MIN_SIZE"), env_i32("MV_GRID")));
        Self { min_size, grid, seen: std::collections::HashSet::new() }
    }

    /// `true` to keep the vector, `false` to drop it.
    ///
    /// `cur_x`/`cur_y` is the block's position in the CURRENT picture, which the
    /// grid buckets on. Callers must pass the right endpoint: the H.264 export
    /// puts the current-picture centre in dst, the HEVC export puts it in src.
    pub fn keep(
        &mut self,
        src_x: i32,
        src_y: i32,
        dst_x: i32,
        dst_y: i32,
        cur_x: i32,
        cur_y: i32,
    ) -> bool {
        if self.min_size > 0 {
            let dx = dst_x - src_x;
            let dy = dst_y - src_y;
            if dx * dx + dy * dy < self.min_size * self.min_size {
                return false;
            }
        }
        if self.grid > 0 {
            // First vector to reach a cell wins; the rest of that cell is dropped.
            if !self.seen.insert((cur_x / self.grid, cur_y / self.grid)) {
                return false;
            }
        }
        true
    }
}

impl Default for MvFilter {
    fn default() -> Self {
        Self::new()
    }
}

/// Convenience wrapper around `MotionVectorCsvWriter<BufWriter<File>>` so
/// extractors don't have to spell out the generics.
pub type FileMvWriter = MotionVectorCsvWriter<BufWriter<File>>;

/// Compact counterpart to `FileMvWriter`, used when the decoder emits
/// `AV_FRAME_DATA_MOTION_VECTORS_COMPACT` instead of the full-size side data.
pub type FileMvCompactWriter = MvCompactCsvWriter<BufWriter<File>>;

/// Open the CSV output file and wrap it in a streaming writer.
pub fn open_mv_writer(path: &str) -> std::io::Result<FileMvWriter> {
    let file = File::create(path)?;
    MotionVectorCsvWriter::new(BufWriter::new(file))
}

pub fn open_mv_compact_writer(path: &str) -> std::io::Result<FileMvCompactWriter> {
    let file = File::create(path)?;
    MvCompactCsvWriter::new(BufWriter::new(file))
}

/// Open an `MvWriter`, picking the compact flavour when the custom FFmpeg
/// feature is enabled and the full flavour otherwise. Keeps the dispatch out
/// of every extractor binary.
pub fn open_mv_any(path: &str) -> std::io::Result<MvWriter> {
    #[cfg(feature = "custom_ffmpeg")]
    {
        Ok(MvWriter::Compact(open_mv_compact_writer(path)?))
    }
    #[cfg(not(feature = "custom_ffmpeg"))]
    {
        Ok(MvWriter::Full(open_mv_writer(path)?))
    }
}

/// Unified writer the extractors hold. Kept as an enum so the same binary can
/// deal with either side-data flavour without pulling feature gates into every
/// call site.
pub enum MvWriter {
    Full(FileMvWriter),
    Compact(FileMvCompactWriter),
}

impl MvWriter {
    pub fn total(&self) -> i64 {
        match self {
            MvWriter::Full(w) => w.total(),
            MvWriter::Compact(w) => w.total(),
        }
    }

    pub fn flush(&mut self) -> std::io::Result<()> {
        match self {
            MvWriter::Full(w) => w.flush(),
            MvWriter::Compact(w) => w.flush(),
        }
    }
}

/// Convert a raw `AVMotionVector` into our shared `MotionVector` type. Any
/// extractor writing to the CSV goes through this so the wire format stays in
/// sync with `mv_types::motion_vector::MV_COLUMNS`.
fn convert_av_mv(frame_num: i32, mv: &AVMotionVector) -> Option<MotionVector> {
    if mv.w == 0 || mv.h == 0 {
        eprintln!(
            "Invalid motion vector dimensions: {} x {}",
            mv.w as i32, mv.h as i32
        );
        return None;
    }
    Some(MotionVector {
        frame: frame_num,
        source: mv.source,
        w: mv.w as i32,
        h: mv.h as i32,
        src_x: mv.src_x as f64,
        src_y: mv.src_y as f64,
        dst_x: mv.dst_x as f64,
        dst_y: mv.dst_y as f64,
        flags: mv.flags,
        motion_x: mv.motion_x as f64,
        motion_y: mv.motion_y as f64,
        motion_scale: mv.motion_scale as f64,
    })
}

/// Append every motion vector from a frame's side-data blob to the writer.
///
/// # Safety
/// `mvs` must point to `size_bytes / size_of::<AVMotionVector>()` valid,
/// contiguous `AVMotionVector`s — exactly the pointer/size pair produced by
/// `av_frame_get_side_data` on `AV_FRAME_DATA_MOTION_VECTORS`.
pub unsafe fn write_side_data(
    writer: &mut FileMvWriter,
    frame_num: i32,
    mvs: *const AVMotionVector,
    size_bytes: usize,
) {
    if mvs.is_null() {
        eprintln!("Invalid motion vector");
        return;
    }
    let count = size_bytes / std::mem::size_of::<AVMotionVector>();
    for i in 0..count {
        let av = unsafe { &*mvs.add(i) };
        if let Some(v) = convert_av_mv(frame_num, av) {
            if let Err(e) = writer.write(&v) {
                eprintln!("Failed to write motion vector: {}", e);
                return;
            }
        }
    }
}

#[cfg(feature = "custom_ffmpeg")]
fn convert_av_mv_compact(frame_num: i32, mv: &AVMotionVectorCompact) -> MvCompact {
    MvCompact {
        frame: frame_num,
        source: mv.source,
        src_x: mv.src_x,
        src_y: mv.src_y,
        dst_x: mv.dst_x,
        dst_y: mv.dst_y,
    }
}

/// Compact counterpart to `write_side_data`. Reads a contiguous array of
/// `AVMotionVectorCompact` produced by the custom FFmpeg patch when
/// `motion_vectors_only=1` and appends each one to the compact writer.
///
/// # Safety
/// Same contract as `write_side_data` but for `AVMotionVectorCompact`.
#[cfg(feature = "custom_ffmpeg")]
pub unsafe fn write_side_data_compact(
    writer: &mut FileMvCompactWriter,
    frame_num: i32,
    mvs: *const AVMotionVectorCompact,
    size_bytes: usize,
) {
    if mvs.is_null() {
        eprintln!("Invalid motion vector");
        return;
    }
    let count = size_bytes / std::mem::size_of::<AVMotionVectorCompact>();
    for i in 0..count {
        let av = unsafe { &*mvs.add(i) };
        let v = convert_av_mv_compact(frame_num, av);
        if let Err(e) = writer.write(&v) {
            eprintln!("Failed to write motion vector: {}", e);
            return;
        }
    }
}

/// Pull motion vectors off a decoded frame and feed them to the writer,
/// picking the compact or full side-data slot based on what the decoder
/// populated. Returns `true` if any side data was found.
///
/// When built with `custom_ffmpeg`, `AV_FRAME_DATA_MOTION_VECTORS_COMPACT`
/// is checked first — the custom decoder populates exactly one of the two
/// slots based on `motion_vectors_only`.
///
/// # Safety
/// `frame` must be a valid, non-null `*mut AVFrame` owned by the caller.
pub unsafe fn write_frame_mvs(
    writer: &mut MvWriter,
    frame_num: i32,
    frame: *mut ff::AVFrame,
) -> bool {
    #[cfg(feature = "custom_ffmpeg")]
    if let MvWriter::Compact(w) = writer {
        // AV_FRAME_DATA_MOTION_VECTORS_COMPACT = 31 in the custom FFmpeg enum.
        // ffmpeg-sys-next generates AVFrameSideDataType as i32; transmute via
        // the integer repr to avoid UB on an undefined discriminant.
        let compact_type: ff::AVFrameSideDataType =
            core::mem::transmute::<i32, ff::AVFrameSideDataType>(31i32);
        let sd = ff::av_frame_get_side_data(frame, compact_type);
        if !sd.is_null() && !(*sd).data.is_null() && (*sd).size > 0 {
            write_side_data_compact(
                w,
                frame_num,
                (*sd).data as *const AVMotionVectorCompact,
                (*sd).size as usize,
            );
            return true;
        }
        // motion_vectors_only=1 not applied at runtime — convert standard
        // AVMotionVector side data to compact format (drops w/h/flags fields).
        let sd_std = ff::av_frame_get_side_data(
            frame,
            ff::AVFrameSideDataType::AV_FRAME_DATA_MOTION_VECTORS,
        );
        if !sd_std.is_null() && !(*sd_std).data.is_null() && (*sd_std).size > 0 {
            let count =
                (*sd_std).size as usize / core::mem::size_of::<ff::AVMotionVector>();
            for i in 0..count {
                let av = &*((*sd_std).data as *const ff::AVMotionVector).add(i);
                let compact = AVMotionVectorCompact {
                    source: av.source,
                    src_x: av.src_x,
                    src_y: av.src_y,
                    dst_x: av.dst_x,
                    dst_y: av.dst_y,
                };
                let v = convert_av_mv_compact(frame_num, &compact);
                if let Err(e) = w.write(&v) {
                    eprintln!("Failed to write compact MV: {}", e);
                    return false;
                }
            }
            return count > 0;
        }
        return false;
    }

    if let MvWriter::Full(w) = writer {
        let sd = ff::av_frame_get_side_data(
            frame,
            ff::AVFrameSideDataType::AV_FRAME_DATA_MOTION_VECTORS,
        );
        if !sd.is_null() && !(*sd).data.is_null() && (*sd).size > 0 {
            write_side_data(
                w,
                frame_num,
                (*sd).data as *const AVMotionVector,
                (*sd).size as usize,
            );
            return true;
        }
    }
    false
}

/// Return the current resident set size of this process in kilobytes,
/// or 0 if it cannot be read.
///
/// Linux: parses `/proc/self/status` (VmRSS). This reflects the *current*
/// RSS after `exec`, unlike `ru_maxrss` from `wait4`.
/// Windows: queries `GetProcessMemoryInfo` via psapi.
/// Other unix: returns 0 (no portable equivalent without extra deps).
#[cfg(target_os = "linux")]
pub fn get_current_rss_kb() -> i64 {
    let Ok(status) = std::fs::read_to_string("/proc/self/status") else {
        return 0;
    };
    for line in status.lines() {
        if let Some(val) = line.strip_prefix("VmRSS:") {
            let val = val.trim().trim_end_matches(" kB").trim();
            return val.parse().unwrap_or(0);
        }
    }
    0
}

#[cfg(target_os = "windows")]
pub fn get_current_rss_kb() -> i64 {
    use std::mem;
    #[repr(C)]
    struct ProcessMemoryCounters {
        cb: u32,
        page_fault_count: u32,
        peak_working_set_size: usize,
        working_set_size: usize,
        quota_peak_paged_pool_usage: usize,
        quota_paged_pool_usage: usize,
        quota_peak_non_paged_pool_usage: usize,
        quota_non_paged_pool_usage: usize,
        pagefile_usage: usize,
        peak_pagefile_usage: usize,
    }
    type Handle = *mut core::ffi::c_void;
    // K32GetProcessMemoryInfo lives in kernel32 (Vista+), so no extra .lib
    // link is needed. The legacy psapi entry point requires psapi.lib.
    #[link(name = "kernel32")]
    extern "system" {
        fn GetCurrentProcess() -> Handle;
        fn K32GetProcessMemoryInfo(
            process: Handle,
            counters: *mut ProcessMemoryCounters,
            cb: u32,
        ) -> i32;
    }
    unsafe {
        let mut pmc: ProcessMemoryCounters = mem::zeroed();
        pmc.cb = mem::size_of::<ProcessMemoryCounters>() as u32;
        if K32GetProcessMemoryInfo(GetCurrentProcess(), &mut pmc, pmc.cb) != 0 {
            (pmc.working_set_size / 1024) as i64
        } else {
            0
        }
    }
}

/// Print the FFmpeg runtime version to stderr.
pub fn print_ffmpeg_version() {
    unsafe {
        let v = CStr::from_ptr(ff::av_version_info()).to_string_lossy();
        eprintln!("FFmpeg version: {}", v);
    }
}

pub unsafe fn set_av_flags(fmt_ctx: &mut ff::AVFormatContext) -> Vec<*mut ff::AVDictionary> {
    let nb_streams = (*fmt_ctx).nb_streams as usize;
    let mut stream_opts: Vec<*mut ff::AVDictionary> = vec![ptr::null_mut(); nb_streams];

    let mv_only_key = CString::new("motion_vectors_only").unwrap();
    let mv_only_val = CString::new("1").unwrap();
    let export_key = CString::new("export_side_data").unwrap();
    let export_val = CString::new("+mvs").unwrap();

    for i in 0..nb_streams {
        ff::av_dict_set(&mut stream_opts[i], mv_only_key.as_ptr(), mv_only_val.as_ptr(), 0);
        ff::av_dict_set(&mut stream_opts[i], export_key.as_ptr(), export_val.as_ptr(), 0);
    }

    stream_opts
}

pub unsafe fn unset_av_flags(stream_opts: Vec<*mut ff::AVDictionary>) { 
    for mut dict in stream_opts {
        if !dict.is_null() {
            ff::av_dict_free(&mut dict);
        }
    }
}